//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class siparis
    {
        public int siparisID { get; set; }
        public int ogrenciID { get; set; }
        public int urunID { get; set; }
    
        public virtual ogrenci ogrenci { get; set; }
        public virtual urun urun { get; set; }
    }
}
